const STATUS_OK = 200;
const STATUS_CREATE = 201;
const ERROR_SERVER = 500;
const ERROR_BADREQUEST = 400;
const ERROR_NOTFOUND = 404;

module.exports = {
  STATUS_OK, STATUS_CREATE, ERROR_SERVER, ERROR_BADREQUEST, ERROR_NOTFOUND,
};
